[package]
name = "marching_cubes"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.99"
